id: swagger-api

info:
  name: Public Swagger API - Detect
  author: pdteam,c-sh0
  severity: info
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 59
    shodan-query: "http.title:\"swagger\""
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - "/swagger-ui/swagger-ui.js"
        - "/swagger/swagger-ui.js"
        - "/swagger-ui.js"
        - "/swagger/ui/swagger-ui.js"
        - "/swagger/ui/index"
        - "/swagger/index.html"
        - "/swagger-ui.html"
        - "/swagger/swagger-ui.html"
        - "/api/swagger-ui.html"
        - "/api-docs/swagger.json"
        - "/api-docs/swagger.yaml"
        - "/api_docs"
        - "/swagger.json"
        - "/swagger.yaml"
        - "/swagger/v1/swagger.json"
        - "/swagger/v1/swagger.yaml"
        - "/api/index.html"
        - "/api/doc"
        - "/api/docs/"
        - "/api/swagger.json"
        - "/api/swagger.yaml"
        - "/api/swagger.yml"
        - "/api/swagger/index.html"
        - "/api/swagger-ui.html"
        - "/api/swagger-ui/swagger.json"
        - "/api/swagger-ui/swagger.yaml"
        - "/api/api-docs/swagger.json"
        - "/api/api-docs/swagger.yaml"
        - "/api/apidocs/swagger.json"
        - "/api/apidocs/swagger.yaml"
        - "/api/swagger-ui/api-docs"
        - "/api/doc.json"
        - "/api/api-docs"
        - "/api/apidocs"
        - "/api/swagger"
        - "/api/swagger/static/index.html"
        - "/api/swagger-resources"
        - "/api/swagger-resources/restservices/v2/api-docs"
        - "/api/__swagger__/"
        - "/api/_swagger_/"
        - "/api/spec/swagger.json"
        - "/api/spec/swagger.yaml"
        - "/api/swagger/ui/index"
        - "/__swagger__/"
        - "/_swagger_/"
        - "/api/v1/swagger-ui/swagger.json"
        - "/api/v1/swagger-ui/swagger.yaml"
        - "/swagger-resources/restservices/v2/api-docs"
        - "/api/swagger_doc.json"
        - "/docu"
        - "/docs"
        - "/swagger"
        - "/api-doc"
        - "/doc/"
        - "/swagger-ui/springfox.js"
        - "/swagger-ui/swagger-ui-standalone-preset.js"
        - "/swagger-ui/swagger-ui/swagger-ui-bundle.js"
        - "/webjars/swagger-ui/swagger-ui-bundle.js"
        - "/webjars/swagger-ui/index.html"
        - "3.0.0/swagger-ui.html"
        - "MobiControl/api/docs/index/index.html"
        - "Swagger"
        - "Swagger/"
        - "Swagger/index.html"
        - "V2/api-docs/ui"
        - "admin/swagger-ui/index.html"
        - "api-doc/"
        - "api-docs/"
        - "api-docs/ui/"
        - "api-docs/v1/index.html"
        - "api-documentation/index.html"
        - "api/"
        - "api/api-docs"
        - "api/api-docs/index.html"
        - "api/api/"
        - "api/apidocs"
        - "api/config"
        - "api/doc"
        - "api/doc/"
        - "api/spec/"
        - "spec/"
        - "api/docs/"
        - "api/docs/index.html"
        - "api/help/swagger-console.html"
        - "api/index.html"
        - "api/swagger"
        - "api/swagger-ui.html"
        - "api/swagger-ui/api-docs"
        - "api/swagger/index.html"
        - "api/swagger/static/index.html"
        - "api/swagger/swagger-ui.html"
        - "api/swagger/ui/index"
        - "api/v0/docs"
        - "api/v1/doc"
        - "api/v1/docs"
        - "api/v1/docs/"
        - "api/v1/swagger-ui.html"
        - "api/v1/swagger-ui/index.html"
        - "api/v1/swagger/"
        - "api/v2/doc"
        - "api/v2/swagger-ui.html"
        - "api/v2/swagger/"
        - "api/v3/swagger-ui.html"
        - "api/v3/swagger/"
        - "api/webjars/swagger-ui/index.html"
        - "apidocs/"
        - "apidocs/index.html"
        - "appcompliance/swagger-ui/index.html"
        - "assets/lib/swagger-ui/index.html"
        - "assets/swagger-ui/index.html"
        - "auth/swagger-ui/"
        - "content-exploration/swagger-ui/index.html"
        - "content/swagger-ui/index.html"
        - "cowboy/webjars/swagger-ui/index.html"
        - "de_de/swagger/"
        - "doc/api-docs/index.html"
        - "docs"
        - "docs/aggregation-protocol/api/swagger/"
        - "docs/api-docs/index.html"
        - "docs/api/"
        - "docs/docs/swagger"
        - "docs/index.html"
        - "docs/static/index.html"
        - "docs/swagger-ui.html"
        - "docs/swagger-ui/index.html"
        - "docs/swagger/index.html"
        - "docs/ui"
        - "documentation/swagger-ui.html"
        - "gateway/swagger-ui/"
        - "harmony/swagger-ui.html"
        - "help/swagger-console.html"
        - "image/swagger-ui.html"
        - "metadata/api-docs/"
        - "mobicontrol/api/docs/index/index.html"
        - "myidtravel/webjars/swagger-ui/index.html"
        - "offer/swagger/index.html"
        - "openam/api/"
        - "reporting/swagger-ui/index.html"
        - "resources/swagger-ui.html"
        - "resources/swagger/index.html"
        - "rest-api/doc/index.html"
        - "rest/swagger-ui/"
        - "services/swagger-ui.html"
        - "springfox-swagger-ui/3.0.0/swagger-ui.html"
        - "ssows/swagger/index.html"
        - "static/api/index.html"
        - "static/swagger_ui/index.html"
        - "swagger"
        - "swagger-resources/configuration/security"
        - "swagger-resources/configuration/ui"
        - "swagger-ui.html"
        - "swagger-ui/"
        - "swagger-ui/index.html"
        - "swagger-ui/vendor"
        - "swagger/"
        - "swagger/api-docs/"
        - "swagger/dist/index.html"
        - "swagger/document"
        - "swagger/index.html"
        - "swagger/index.htmlindex.html"
        - "swagger/static/index.html"
        - "swagger/swagger-ui.html"
        - "swagger/ui/index"
        - "swagger/ui/"
        - "swaggerui/"
        - "swaggerui/index.html"
        - "twintweb/swaggerui/"
        - "v1/api-docs/"
        - "v1/api-docs/index.html"
        - "v1/swagger-ui.html"
        - "v3/api-docs/ui"
        - "webapi/index.html"
        - "webapi/swagger/index.html"
        - "webjars/springfox-swagger-ui/3.0.0/swagger-ui.html"
        - "webjars/swagger-ui/2.2.5/index.html"
        - "webjars/swagger-ui/index.html"

    headers:
      Accept: text/html

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "loadSwaggerUI"
          - "**token**:"
          - "id=\"swagger-ui"
          - "openapi:"
          - "{\"openapi\":" 
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"

